name: ci

on:
  push:
    branches: [ "main" ]
    tags:
      - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build arm64
        run: go build -o ./aucn-arm64 ./cmd/aucn.go
        env:
          GOARCH: arm64
          GOOS: linux

      - name: Build amd64
        run: go build -o ./aucn-amd64 ./cmd/aucn.go
        env:
          GOARCH: amd64
          GOOS: linux

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-result-${{github.sha}}
          path: |
            ./aucn-amd64
            ./aucn-arm64
          retention-days: 1

  release:
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: build-result-${{github.sha}}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,aucn-arm64,aucn-amd64"